---
sudo: true
language: rust
rust:
  - stable
  - nightly
  - beta

before_install:
  - sudo add-apt-repository -y ppa:kalakris/cmake
  - sudo add-apt-repository -y ppa:team-xbmc/ppa
  - sudo apt-get update -qq

install:
  - sudo apt-get install libXxf86vm-dev cmake libsdl2-dev

os:
  - linux

env:
  global:
    - LD_LIBRARY_PATH: /usr/local/lib

matrix:
  allow_failures:
    - rust: 1.3.0

branches:
  only:
    - master

env:
  - ARCH=x86_64
  - ARCH=i686

script:
  - cargo build
  - cargo test

addons:
  apt:
    packages:
      - gcc-multilib
