---
sudo: false
language: rust
rust:
  - 1.3.0
  - stable
  - nightly
  - beta

install:
    brew install libsdl2-dev


os:
  - osx

env:
    global:
          - LD_LIBRARY_PATH: /usr/local/lib

branches:
  only:
    - display

env:
  - ARCH=x86_64
  - ARCH=i686

matrix:
  allow_failures:
    - rust: 1.3.0
    - rust: stable
    - rust: beta

script:
  - cargo build
  - cargo test

addons:
  apt:
    packages:
      - gcc-multilib

