---
sudo: true
language: rust
rust:
  - 1.3.0
  - stable
  - nightly
  - beta

before_install:
  - sudo add-apt-repository -y ppa:kalakris/cmake
  - sudo add-apt-repository -y ppa:team-xbmc/ppa
  - sudo apt-get update -qq

install:
  - sudo apt-get install libXxf86vm-dev cmake libsdl2-dev

os:
  - linux

branches:
  only:
    - master
    - display

env:
  global:
    - LD_LIBRARY_PATH: /usr/local/lib

env:
  - ARCH=x86_64
  - ARCH=i686

matrix:
  allow_failures:
    - rust: 1.3.0
    - rust: stable
    - rust: beta

branches:
  only:
    - master

script:
  - cargo build
  - cargo test

addons:
  apt:
    packages:
      - gcc-multilib
