---
sudo: false
language: rust
rust:
  - 1.3.0
  - stable
  - nightly
  - beta

os:
  - linux
  - osx

branches:
  only:
    - master

env:
  - ARCH=x86_64
  - ARCH=i686

matrix:
  allow_failures:
    - rust: stable
    - rust: 1.3.0

script:
  - cargo build

addons:
  apt:
    packages:
      - gcc-multilib
