---
sudo: true
language: rust
rust:
  - 1.3.0
  - stable
  - nightly
  - beta

install:
  - linux
    [ $TRAVIS_BRANCH = display ] && sudo apt-get install libsdl2-dev
  - mac
    [ $TRAVIS_BRANCH = display ] && brew install libsdl2-dev


os:
  - linux
  - osx

env:
    global:
          - LD_LIBRARY_PATH: /usr/local/lib

branches:
  only:
    - master
    - display

env:
  - ARCH=x86_64
  - ARCH=i686

matrix:
  allow_failures:
    - rust: 1.3.0
    - rust: stable
    - rust: beta

script:
  - cargo build
  - cargo test
addons:
  apt:
    packages:
      - gcc-multilib

