[package]
name = "lemipc"
version = "0.1.0"
authors = ["adjivas <adjivas@users.noreply.github.com>"]
description = "subject of lemipc game"

[[bin]]
name = "lemipc"
doc = false

[dependencies.sem]
git = "https://github.com/adjivas/sem.git"

[dependencies.shm]
git = "https://github.com/adjivas/shm.git"

[dependencies.sig]
git = "https://github.com/adjivas/sig.git"

[dependencies.msg]
git = "https://github.com/adjivas/msg.git"

[dependencies.io]
git = "https://github.com/adjivas/io.git"

[features]
signal = []
